### ISSUE TITLE
`argparse.ArgumentParser` does not expect `version` argument

### ISSUE THREAD

**Issue by amiv1** [kofrasa/migrate#2]
`version` parameter doesn't exist which causes an exception to be thrown when launching `migrate` or `test_migrate`.

```
Traceback (most recent call last):
  File "migrate.py", line 328, in <module>
    main()
  File "migrate.py", line 262, in main
    """)
TypeError: __init__() got an unexpected keyword argument 'version'
```

```
======================================================================
ERROR: test_config_file (__main__.MigrateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_migrate.py", line 92, in test_config_file
    migrate.main('-f', filename, '--env', 'test', 'reset')
  File "/home/gim/Workspace/migrate/migrate.py", line 262, in main
    """)
TypeError: __init__() got an unexpected keyword argument 'version'
```

https://docs.python.org/3.5/library/argparse.html#argparse.ArgumentParser
Python version: 3.5.1

**Comment by kofrasa** [comment]
It seems the api for `ArgumentParser` has become rather strict like many other things in python3.5.
