### ISSUE TITLE
The `pwd` package is missing in Windows OS

### ISSUE THREAD

**Issue by vkvych** [kofrasa/migrate#7]
Unable to install the **migrate** package on Windows 10 OS:

```
(venv) C:\Users\vkvych\Projects\migrate-test>python --version
Python 3.6.1

(venv) C:\Users\vkvych\Projects\migrate-test>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pip (9.0.1)
setuptools (38.2.3)

(venv) C:\Users\vkvych\Projects\migrate-test>pip install migrate
Collecting migrate
  Using cached migrate-0.3.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\vkvych\AppData\Local\Temp\pip-build-23l1g8c8\migrate\setup.py", line 26, in <module>
        import migrate
      File "C:\Users\vkvych\AppData\Local\Temp\pip-build-23l1g8c8\migrate\migrate.py", line 18, in <module>
        import pwd
    ModuleNotFoundError: No module named 'pwd'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\vkvych\AppData\Local\Temp\pip-build-23l1g8c8\migrate\
```

**Comment by kofrasa** [comment]
I will update pip with a new release
